### ISSUE TITLE
Does not run

### ISSUE THREAD

**Issue by sigma415** [ggow/DiskLED#4]
Originally I did search for a Disk LED tool for Windows 11, but this program doesn't even run on Windows 10.
After about 1 second system tray icon disappeared and program has stopped without any error message.

**Comment by ggow** [comment]
> Originally I did search for a Disk LED tool for Windows 11, but this program doesn't even run on Windows 10. After about 1 second system tray icon disappeared and program has stopped without any error message.

Have you got the .net 4.8 runtime installed?

If you haven't try downloading and installing the runtime from here:
https://dotnet.microsoft.com/en-us/download/dotnet-framework/net48

**Comment by sigma415** [comment]
Yes, running web installer ndp48-web.exe it says:

```
Details

.NET Framework 4.8 oder ein neueres Update ist bereits auf diesem Computer installiert.
```

And running "DotNetVersions.exe" tool it shows as result:

```
Currently installed "classic" .NET Versions in the system:
2.0.50727.4927 Service Pack 2
3.0.30729.4926 Service Pack 2
3.5.30729.4926 Service Pack 1
4.0.0.0
4.8.04084
```

I also tried running diskled.exe as admin=  same result

**Comment by ggow** [comment]
I just ran this on windows 10 and it worked fine. Windows 10 was installed clean with updates.

**Comment by ggow** [comment]
Could not reproduce fault
